server.port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ap?useSSL=false&serverTimezone=Europe/Warsaw
    username: ap
    password: xxx
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties.hibernate.format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.xml
